name: Woff2 Decompress

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    
    strategy:
      fail-fast: false

      
    steps:

    - name: Checkout curent repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Clone Woff2
      run: |
        git clone --recursive https://github.com/google/woff2.git
        
    - name: Build Woff2
      run: |
        cd woff2
        make clean all

    - name: Decompress Woff2 fonts
      run: |
        ./woff2/woff2_decompress ./material-symbols/material-symbols-outlined.woff2
        ./woff2/woff2_decompress ./material-symbols/material-symbols-rounded.woff2
        ./woff2/woff2_decompress ./material-symbols/material-symbols-sharp.woff2

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ttf
        path: ./material-symbols

    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Add compiled files"
        commit_options: "--no-verify"
        file_pattern: "material-symbols/*.ttf"
        name: "o-murphy"
        email: "thehelixpg@gmail.com"
        push: true
        # branch: "woff2-decompress"  # Replace with your branch name
        
